const initialProducts = [
  {
    id: 1,
    name: "Рыцарский меч",
    category: "Мечи",
    description: "Одноручный рыцарский меч для боя в связке со щитом.",
    era: "XIII век",
    origin: "Западная Европа",
    material: "Сварной стальной клинок, деревянная рукоять",
    price: 28900,
    stock: 12,
    rating: 4.9,
    image: "/assets/products/arming-sword.jpg"
  },
  {
    id: 2,
    name: "Длинный меч",
    category: "Мечи",
    description: "Двуручный клинок позднего Средневековья для фехтовальных школ.",
    era: "XIV-XV века",
    origin: "Священная Римская империя",
    material: "Высокоуглеродистая сталь",
    price: 34600,
    stock: 9,
    rating: 4.9,
    image: "/assets/products/longsword.jpg"
  },
  {
    id: 3,
    name: "Фальшион",
    category: "Мечи",
    description: "Рубящий однолезвийный меч с широким клинком.",
    era: "XIII век",
    origin: "Англия и Франция",
    material: "Стальной клинок, роговая рукоять",
    price: 25400,
    stock: 7,
    rating: 4.6,
    image: "/assets/products/falchion.jpg"
  },
  {
    id: 4,
    name: "Мессер",
    category: "Мечи",
    description: "Крупный нож-меч, популярный у городских ополчений.",
    era: "XV век",
    origin: "Германские земли",
    material: "Стальной клинок, деревянные накладки рукояти",
    price: 23800,
    stock: 11,
    rating: 4.5,
    image: "/assets/products/messer.jpg"
  },
  {
    id: 5,
    name: "Датский боевой топор",
    category: "Топоры",
    description: "Длиннодревковый топор для плотного пехотного строя.",
    era: "XI век",
    origin: "Скандинавия и Англия",
    material: "Стальное лезвие, ясеневая рукоять",
    price: 27100,
    stock: 8,
    rating: 4.7,
    image: "/assets/products/dane-axe.jpg"
  },
  {
    id: 6,
    name: "Бородатый топор",
    category: "Топоры",
    description: "Топор с вытянутой нижней кромкой для зацепа и контроля оружия.",
    era: "X-XII века",
    origin: "Скандинавия",
    material: "Железная основа, стальная кромка",
    price: 21900,
    stock: 14,
    rating: 4.6,
    image: "/assets/products/bearded-axe.jpg"
  },
  {
    id: 7,
    name: "Шестопер",
    category: "Ударное оружие",
    description: "Дробящее оружие с металлическими перьями для поражения доспеха.",
    era: "XIV-XVI века",
    origin: "Центральная Европа",
    material: "Стальная боевая часть, твердая деревянная рукоять",
    price: 20600,
    stock: 10,
    rating: 4.4,
    image: "/assets/products/flanged-mace.jpg"
  },
  {
    id: 8,
    name: "Люцернский молот",
    category: "Ударное оружие",
    description: "Древковый молот с клювом и шипом против латной брони.",
    era: "XV век",
    origin: "Швейцарские кантоны",
    material: "Стальная головка, ясеневое древко",
    price: 29400,
    stock: 6,
    rating: 4.8,
    image: "/assets/products/lucerne-hammer.jpg"
  },
  {
    id: 9,
    name: "Копье",
    category: "Древковое оружие",
    description: "Универсальное колющее оружие для ополчения и линейной пехоты.",
    era: "XI-XV века",
    origin: "Европа",
    material: "Стальной наконечник, ясеневое древко",
    price: 16200,
    stock: 18,
    rating: 4.3,
    image: "/assets/products/spear.jpg"
  },
  {
    id: 10,
    name: "Алебарда",
    category: "Древковое оружие",
    description: "Комбинация топора, крюка и копья для борьбы с конницей.",
    era: "XV век",
    origin: "Швейцария и Южная Германия",
    material: "Стальная головка, твердое деревянное древко",
    price: 31700,
    stock: 7,
    rating: 4.8,
    image: "/assets/products/halberd.jpg"
  },
  {
    id: 11,
    name: "Полэкс",
    category: "Древковое оружие",
    description: "Дворянское древковое оружие для пешего боя в доспехах.",
    era: "XV век",
    origin: "Франция и Бургундия",
    material: "Стальная головка, дубовое древко с лангетами",
    price: 33200,
    stock: 5,
    rating: 4.8,
    image: "/assets/products/pollaxe.jpg"
  },
  {
    id: 12,
    name: "Английский длинный лук",
    category: "Дистанционное оружие",
    description: "Мощный лук большого натяжения, связанный с английской военной традицией.",
    era: "XIII-XV века",
    origin: "Англия и Уэльс",
    material: "Тис, льняная тетива",
    price: 24100,
    stock: 13,
    rating: 4.7,
    image: "/assets/products/english-longbow.jpg"
  },
  {
    id: 13,
    name: "Составной рекурсивный лук",
    category: "Дистанционное оружие",
    description: "Составная конструкция из рога и дерева, эффективная для конных лучников.",
    era: "XIII век",
    origin: "Евразийская степь",
    material: "Рог, дерево, сухожилия, животный клей",
    price: 27800,
    stock: 9,
    rating: 4.7,
    image: "/assets/products/composite-bow.jpg"
  },
  {
    id: 14,
    name: "Арбалет с воротом",
    category: "Дистанционное оружие",
    description: "Тяжелый арбалет со стальным луком и механическим взводом.",
    era: "XV век",
    origin: "Итальянские города-государства",
    material: "Стальной лук, ореховое ложе",
    price: 36400,
    stock: 6,
    rating: 4.8,
    image: "/assets/products/windlass-crossbow.jpg"
  },
  {
    id: 15,
    name: "Каплевидный щит",
    category: "Щиты",
    description: "Рыцарский щит для конного боя и защиты корпуса.",
    era: "XII-XIII века",
    origin: "Западная Европа",
    material: "Ламинированное дерево, сыромятное покрытие",
    price: 14800,
    stock: 16,
    rating: 4.3,
    image: "/assets/products/heater-shield.jpg"
  },
  {
    id: 16,
    name: "Павеза",
    category: "Щиты",
    description: "Крупный щит для арбалетчиков и осадной обороны.",
    era: "XIV-XV века",
    origin: "Северная Италия",
    material: "Деревянная основа, холст и грунт",
    price: 22600,
    stock: 8,
    rating: 4.5,
    image: "/assets/products/pavise-shield.jpg"
  },
  {
    id: 17,
    name: "Круглый щит",
    category: "Щиты",
    description: "Щит с центральным умбоном для подвижного боя.",
    era: "X-XI века",
    origin: "Северная Европа",
    material: "Деревянные плашки, железный умбон",
    price: 13100,
    stock: 20,
    rating: 4.2,
    image: "/assets/products/round-shield.jpg"
  },
  {
    id: 18,
    name: "Баклер",
    category: "Щиты",
    description: "Малый кулачный щит для парирования в паре с мечом.",
    era: "XIII-XVI века",
    origin: "Западная и Центральная Европа",
    material: "Стальная пластина",
    price: 9800,
    stock: 24,
    rating: 4.1,
    image: "/assets/products/buckler.jpg"
  },
  {
    id: 19,
    name: "Кольчужный хауберк",
    category: "Броня",
    description: "Длинная кольчужная рубаха с рукавами из клепаных колец.",
    era: "XI-XIII века",
    origin: "Европа и Ближний Восток",
    material: "Клепаные железные кольца",
    price: 39200,
    stock: 6,
    rating: 4.8,
    image: "/assets/products/mail-hauberk.jpg"
  },
  {
    id: 20,
    name: "Котта с пластинами",
    category: "Броня",
    description: "Скрытые металлические пластины, закрепленные под тканевой оболочкой.",
    era: "XIII-XIV века",
    origin: "Центральная Европа",
    material: "Железные пластины, лен, кожа",
    price: 33800,
    stock: 7,
    rating: 4.6,
    image: "/assets/products/coat-of-plates.jpg"
  },
  {
    id: 21,
    name: "Бригандина",
    category: "Броня",
    description: "Гибкий доспех из множества внутренних металлических пластин.",
    era: "XV век",
    origin: "Италия и Франция",
    material: "Стальные пластины, плотная ткань",
    price: 35100,
    stock: 8,
    rating: 4.7,
    image: "/assets/products/brigandine.jpg"
  },
  {
    id: 22,
    name: "Гамбезон",
    category: "Броня",
    description: "Стеганая защитная одежда, носимая под латами или отдельно.",
    era: "XII-XV века",
    origin: "Европа",
    material: "Многослойный лен с шерстяной набивкой",
    price: 12300,
    stock: 22,
    rating: 4.2,
    image: "/assets/products/gambeson.jpg"
  },
  {
    id: 23,
    name: "Бацинет",
    category: "Шлемы",
    description: "Шлем с возможным забралом и кольчужным бармицей.",
    era: "XIV век",
    origin: "Западная Европа",
    material: "Кованая сталь",
    price: 27100,
    stock: 10,
    rating: 4.5,
    image: "/assets/products/bascinet.jpg"
  },
  {
    id: 24,
    name: "Салад",
    category: "Шлемы",
    description: "Позднесредневековый шлем с вытянутой защитой затылка.",
    era: "XV век",
    origin: "Германия и Италия",
    material: "Сталь с кожаным подшлемником",
    price: 25900,
    stock: 9,
    rating: 4.4,
    image: "/assets/products/sallet.jpg"
  },
  {
    id: 25,
    name: "Большой шлем",
    category: "Шлемы",
    description: "Закрытый цилиндрический шлем эпохи высокого Средневековья.",
    era: "XIII век",
    origin: "Западная Европа",
    material: "Клепаные стальные пластины",
    price: 30400,
    stock: 5,
    rating: 4.3,
    image: "/assets/products/great-helm.jpg"
  },
  {
    id: 26,
    name: "Латные перчатки",
    category: "Перчатки",
    description: "Сегментная защита кистей для меча и древкового оружия.",
    era: "XIV век",
    origin: "Итальянские мастерские",
    material: "Стальные пластины, кожаная основа",
    price: 18900,
    stock: 12,
    rating: 4.5,
    image: "/assets/products/hourglass-gauntlets.jpg"
  },
  {
    id: 27,
    name: "Сабатоны",
    category: "Элементы брони",
    description: "Сегментная защита стопы для полного латного гарнитура.",
    era: "XV век",
    origin: "Германия",
    material: "Сочлененные стальные пластины",
    price: 17400,
    stock: 9,
    rating: 4.2,
    image: "/assets/products/sabatons.jpg"
  },
  {
    id: 28,
    name: "Горжет",
    category: "Элементы брони",
    description: "Пластинчатая защита шеи и верхней части груди.",
    era: "XV-XVI века",
    origin: "Западная Европа",
    material: "Стальные пластины и ремни",
    price: 14100,
    stock: 15,
    rating: 4.1,
    image: "/assets/products/gorget.jpg"
  },
  {
    id: 29,
    name: "Рондельный кинжал",
    category: "Кинжалы",
    description: "Жесткий колющий кинжал для поражения уязвимых зон доспеха.",
    era: "XIV-XV века",
    origin: "Западная Европа",
    material: "Стальной клинок и круглые упоры",
    price: 11900,
    stock: 19,
    rating: 4.4,
    image: "/assets/products/rondel-dagger.jpg"
  },
  {
    id: 30,
    name: "Базелард",
    category: "Кинжалы",
    description: "Двулезвийный кинжал, распространенный как гражданское и военное оружие.",
    era: "XIV век",
    origin: "Швейцария и германские земли",
    material: "Стальной клинок, деревянная рукоять",
    price: 10800,
    stock: 21,
    rating: 4.2,
    image: "/assets/products/baselard.jpg"
  }
];

function cloneProducts() {
  return initialProducts.map((product) => ({ ...product }));
}

module.exports = {
  initialProducts,
  cloneProducts
};
